import base64
import json


RAW_SECRET = None
SECRET = "eyJHT09HTEVfQ0xJRU5UX0lEIjogIjgwNjMwMzYzMDcyMy10ODZxbXIyYnZnMWJxMzI1NWdlamRwYm9zOGozbm9wYS5hcHBzLmdvb2dsZXVzZXJjb250ZW50LmNvbSIsICJHT09HTEVfQ0xJRU5UX1NFQ1JFVCI6ICJHT0NTUFgtVy1OUi1VcWlNRkhhZWdhdEdJQUtGUjNjQkQ1QSIsICJUV0lUVEVSX0NMSUVOVF9JRCI6ICJSbGsxZVZOWVNYRTFWbmgyYzFOVVEwZFNYMnc2TVRwamFRIiwgIlRXSVRURVJfQ0xJRU5UX1NFQ1JFVCI6ICJlX2l2TmdXbnN5dHZEWmN5dEE4S3hSSWYzbGNKRExuaVZoS0dxVTBTYm9DZ3d0T19iaiIsICJTTUFSVFRISU5HU19DTElFTlRfSUQiOiAiMjQ4ZmNhNGItNmY3OS00NDE0LWI2M2YtNGI5NmNiODA3ZTU1IiwgIlNNQVJUVEhJTkdTX0NMSUVOVF9TRUNSRVQiOiAiYjE0MzhkM2UtMGQxOS00ZDVmLTk0YzctNTJmYTU1YjdiYWE5IiwgIllPVVRVQkVfQ0xJRU5UX0lEIjogIjgwNjMwMzYzMDcyMy10ODZxbXIyYnZnMWJxMzI1NWdlamRwYm9zOGozbm9wYS5hcHBzLmdvb2dsZXVzZXJjb250ZW50LmNvbSIsICJZT1VUVUJFX0NMSUVOVF9TRUNSRVQiOiAiR09DU1BYLVctTlItVXFpTUZIYWVnYXRHSUFLRlIzY0JENUEifQ=="

class SecretStorage:
    def __init__(self):
        if SECRET:
            self.secrets = json.loads(base64.b64decode(SECRET))
        else:
            self.secrets = RAW_SECRET

    def to_dict(self):
        return self.secrets

    def get(self, key):
        return self.secrets.get(key)

secret = SecretStorage()